--- #YAML:1.0
name: Class-Classless-DBI
version: 0.01
author:
  - Mark Tiefenbruck <mdash@cpan.org>
abstract: provides a classless object-oriented database interface
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
